name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs 00:00 UTC on Monday
    - cron: "0 0 * * 1"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TIMEZONE: "True"
